server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/dbtest"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  singer_Key: "EiQkd32RE87sxSV4dXklV2WWfqtW32qSu4JPr/WqD1XtIEfmj+1E+PoUdXiPEk+Q"